name: customer_portal
description: "Customer Portal for wdms"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^14.7.0
  firebase_core: ^2.19.0
#  firebase_analytics: ^10.5.1
  firebase_analytics_web: ^0.5.5+21
  firebase_remote_config: ^4.3.15
  firebase_crashlytics: ^3.4.17
  firebase_storage: ^11.6.8
  flutter_local_notifications: ^16.1.0
  flutter_logs: ^2.1.11
  http: ^1.1.0  # Use the latest version available
  logger: ^1.0.0
  dio: ^4.0.6
  provider: ^6.0.0
  dio_logging_interceptor: ^1.0.1
  intl: ^0.18.1
  shared_preferences: ^2.0.0
  simple_animations: ^5.0.2
  flutter_slidable: ^3.0.1
  syncfusion_flutter_datepicker: ^23.1.40
  flutter_svg: ^2.0.9
  image_picker: ^1.0.1
  image_cropper: ^5.0.0
  image: ^3.0.2
  fluttertoast: ^8.2.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/home/outstanding.png
    - assets/home/custody_details.png
    - assets/home/bottle_custody.png
    - assets/home/dispenser.png
    - assets/home/temp_bottle.png
    - assets/home/others.png
    - assets/home/user.png
    - assets/home/location.png
    - assets/home/payment_method.png
    - assets/home/available_coupon.png
    - assets/home/free_coupon.png
    - assets/home/sales.png
    - assets/home/collection.png
    - assets/home/paidcoupon.png
    - assets/home/filter.png
    - assets/bottom_menu/home.png
    - assets/bottom_menu/home_trans.png
    - assets/bottom_menu/profile.png
    - assets/bottom_menu/profile_trans.png
    - assets/bottom_menu/setting.png
    - assets/bottom_menu/setting_trans.png
    - assets/bottom_menu/logout_trans.png
    - assets/bottom_menu/aboutUs.png
    - assets/bottom_menu/aboutUs_trans.png
    - assets/bottom_menu/contact.png
    - assets/bottom_menu/contact_trans.png
    - assets/logo/app_icon.png
    - assets/login/bottom1.png
    - assets/login/bottom2.png
    - assets/login/main.png
    - assets/login/top1.png
    - assets/login/top2.png
    - assets/login/login_background.jpg
    - assets/coupon/bottle.jpg
    - assets/profile/Profile_Image.png
    - assets/profile/Camera_Icon.svg
    - assets/profile/User Icon.svg
    - assets/profile/Bell.svg
    - assets/profile/Settings.svg
    - assets/profile/Question mark.svg
    - assets/profile/Log out.svg
    - assets/profile/telephone.png
    - assets/profile/whatsapp.png
    - assets/profile/customer_type.png
    - assets/profile/joining_date.png
    - assets/profile/delivery.png
    - assets/profile/item.png
    - assets/profile/bottle.png
    - assets/profile/price.png
    - assets/profile/email.png
    - assets/profile/username.png
    - assets/profile/password.png
    - assets/profile/credit_limit.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Thin.otf
          weight: 100
          style: normal
        - asset: fonts/Metropolis-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/Metropolis-ExtraLight.otf
          weight: 200
          style: normal
        - asset: fonts/Metropolis-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/Metropolis-Light.otf
          weight: 300
          style: normal
        - asset: fonts/Metropolis-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/Metropolis-Regular.otf
          weight: 400
          style: normal
        - asset: fonts/Metropolis-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/Metropolis-Medium.otf
          weight: 500
          style: normal
        - asset: fonts/Metropolis-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Metropolis-SemiBold.otf
          weight: 600
          style: normal
        - asset: fonts/Metropolis-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Metropolis-Bold.otf
          weight: 700
          style: normal
        - asset: fonts/Metropolis-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Metropolis-ExtraBold.otf
          weight: 800
          style: normal
        - asset: fonts/Metropolis-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Metropolis-Black.otf
          weight: 900
          style: normal
        - asset: fonts/Metropolis-BlackItalic.otf
          weight: 900
          style: italic

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
